### ISSUE TITLE
How to build a Java array of strings

### ISSUE THREAD

**Issue by fpoli** [kud1ing/rucaja#13]
Is it possible to build a Java array from rucaja?

I would like to call a Java method that takes an array of strings (eg. `void main(String[] args)`), but I can't find how to build the `jvalue' of the array.

```rust
...

let java_string: JvmString = jvm.new_jvm_string("Hello").unwrap();

let args: Vec<jvalue> = vec![
    // ?
];

// Call the main
jvm.call_static_object_method(
    &main_class,
    &main_method,
    args.as_ptr()
);
```

**Comment by kud1ing** [comment]
No sorry. Such a function does not exist (yet).

You'd need to create a String array using the `[type` array specifier https://docs.oracle.com/javase/1.5.0/docs/guide/jni/spec/types.html
Then Java strings would have to be created and set using the Java array method.

I don't have much time for this but i would be happy to merge such a function if provided.

There is also https://github.com/rawrasaur/rust-jvm

**Comment by fpoli** [comment]
Thanks
