### ISSUE TITLE
convert jstring to Rust string buffer

### ISSUE THREAD

**Issue by hongxuchen** [kud1ing/rucaja#14]
The primitive java types have direct mappings in `jni_sys`.

So is there any convenient way to convert *jstring* (e.g., generated by `jvm::call_static_object_method`) to a "str"/"&[u8]"?

In my opinion this should be reasonable since Java String is quite special.
Maybe there should be an additional parameter to keep the length?

**Comment by treyzania** [comment]
You might be able to get a raw `char*` and convert it to a `CStr`/`CString`, and then convert it into whatever you want from there.

**Comment by hongxuchen** [comment]
@treyzania Can you show me some sample code? I'm kind of stuck on the internal representation of `String` and not sure whether it is possible that the area is GCed.

**Comment by treyzania** [comment]
Look into `GetStringUTFChars`, example here: http://leo.ugr.es/elvira/devel/Tutorial/Java/native1.1/implementing/string.html (This is for the JNI, but `jstring` is used outside of just that.)

You'd end up getting an owned copy of the Java string.  Modifying the original it is probably a bad idea as the JVM tends to do "magic" things involving string interning and it could get invalidated unpredictably.  Just make sure you `Release` it afterwards.

Also on StackOverflow: https://stackoverflow.com/questions/4181934/jni-converting-jstring-to-char

**Comment by hongxuchen** [comment]
@treyzania Thanks for the link!

It seems that rucaja hasn't disclosed `JNIEnv` struct right now so may not be possible without modifying the code.

**Comment by kud1ing** [comment]
@HongxuChen I haven't looked into this code for some time, so maybe what i am saying is not helpful: `JvmAttachment` returns the `JNIEnv` in `jni_environment()`. Or did you mean to represent the content of `JNIEnv` in a Rust struct?

**Comment by hongxuchen** [comment]
@treyzania but it's not publicly exported (https://github.com/kud1ing/rucaja/blob/master/src/lib.rs) right?

**Comment by kud1ing** [comment]
True. :( This should be added, but I have to go now.
By the way: https://github.com/rawrasaur/rust-jvm/blob/master/src/string.rs#L32

**Comment by hongxuchen** [comment]
@treyzania Okay, will take a look. Thanks!

**Comment by kud1ing** [comment]
I've added the reexport of `JNIEnv`, implemented `ToString` for `JvmString` and published a new version.

Does this help you to close this issue?
